### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had Inf values

### ISSUE THREAD

**Issue by Ashchenlovelive** [YangzlTHU/VAE-Stega#1]
I run vae_lstm-lstm.py and got the error:

Traceback (most recent call last):
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had Inf values
 \[\[{{node VerifyFinite/CheckNumerics}} = CheckNumerics\[T=DT_FLOAT, message="Found Inf or NaN global norm.", _device="/job:localhost/replica:0/task:0/device:GPU:0"](global_norm/global_norm)]]
 \[\[{{node clip_by_global_norm/mul_1/_93}} = _Recv\[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1424_clip_by_global_norm/mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "vae_lstm-lstm.py", line 272, in <module>
    main(params)
  File "vae_lstm-lstm.py", line 238, in main
    \[qz, lower_bound, optimize, kld, annealing, rec_loss, perplexity], feed_dict=feed)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had Inf values
 \[\[node VerifyFinite/CheckNumerics (defined at vae_lstm-lstm.py:163)  = CheckNumerics\[T=DT_FLOAT, message="Found Inf or NaN global norm.", _device="/job:localhost/replica:0/task:0/device:GPU:0"](global_norm/global_norm)]]
 \[\[{{node clip_by_global_norm/mul_1/_93}} = _Recv\[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1424_clip_by_global_norm/mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
 
Caused by op 'VerifyFinite/CheckNumerics', defined at:
  File "vae_lstm-lstm.py", line 272, in <module>
    main(params)
  File "vae_lstm-lstm.py", line 163, in main
    clipped_grad, _ = tf.clip_by_global_norm(gradients, 5)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/ops/clip_ops.py", line 265, in clip_by_global_norm
    "Found Inf or NaN global norm.")
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/ops/numerics.py", line 47, in verify_tensor_all_finite
    verify_input = array_ops.check_numerics(t, message=msg)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 817, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/public/anaconda2/envs/vae_stega/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()
 
InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had Inf values
 \[\[node VerifyFinite/CheckNumerics (defined at vae_lstm-lstm.py:163)  = CheckNumerics\[T=DT_FLOAT, message="Found Inf or NaN global norm.", _device="/job:localhost/replica:0/task:0/device:GPU:0"](global_norm/global_norm)]]
 \[\[{{node clip_by_global_norm/mul_1/_93}} = _Recv\[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1424_clip_by_global_norm/mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by Ashchenlovelive** [comment]
I found that this problem can be solved by reducing the learning rate, so I closed it.
